### ISSUE TITLE
Uncaught TypeError: e is not a function

### ISSUE THREAD

**Issue by Shooshte** [bretthadley/react-ui-slider#2]
Following this example:
https://github.com/bretthadley/react-ui-slider/blob/master/demo/demosrc.js

I tried implementing the slider:
```
import React from 'react';
import ReactUISlider from 'react-ui-slider';

class Slider extends React.Component {
    constructor(props) {
        super(props);
        this.handleSliderChange = this.handleSliderChange.bind(this);
    }

    handleSliderChange = (value) => {
        console.log("changed", value);
    }

    render() {

        const sliderPropsEven = {
            min: 0,
            max: 100,
            step: 10,
            label: "Deposit",
            labelAfter: "GBP (£)",
            onAfterChange: this.handleSliderChange
        }

        return(
            <div>
                <ReactUISlider { ...sliderPropsEven } />
            </div>
        )
    }
}

Slider.propTypes = {
    totalSeconds: React.PropTypes.number.isRequired,
    onSetCountdown: React.PropTypes.func.isRequired
};

export default Slider;
```

I get the following error in the console, and only the labels render:

> Uncaught TypeError: e is not a function
>     at range-touch.min.js:2
>     at range-touch.min.js:2
> (anonymous) @ range-touch.min.js:2
> (anonymous) @ range-touch.min.js:2

**Comment by bretthadley** [comment]
Hey, I just re-built the demo using the latest React version and I don't the same issue.

See here for an example demo http://bretthadley.github.io/react-ui-slider/demo/

src for demo is here https://github.com/bretthadley/react-ui-slider/blob/master/demo/demosrc.js

**Comment by Shooshte** [comment]
In this demo, you are not loading the script from a CDN (the range-touch-min.js) file. I was including this script in my index, and it returned the error. Maybe there is an issue with the CDN version?

**Comment by bretthadley** [comment]
I'm confused now. This library isn't available on a CDN (as far as I'm aware). I think you may be getting confused with which libraries you're using? The issue appears to be related to the other library you're loading.

Can you provide a link to it?

**Comment by Shooshte** [comment]
You are completely correct, the CDN was from another library I was using. After getting back to it, I was able to re-use your slider.

Thanks for taking the time to look into this anyway.
